#!/bin/bash

morseNumber=0
morseMultiplier=1

for ((i=0; i < ${#1}; i++)); do
    curChar=${1:i:1}
    if [[ $curChar == '.' ]]; then
        (( morseNumber += morseMultiplier ))
    else
        (( morseNumber += morseMultiplier * 2 ))
    fi
    (( morseMultiplier *= 2 ))
done
(( morseNumber-- )) # to start from 0 instead of 1

echo "$morseNumber"
